# explicitly list all rules in use
only_rules:
    - anyobject_protocol
    - block_based_kvo
    - class_delegate_protocol
    - closing_brace
    - closure_end_indentation
    - closure_parameter_position
    - closure_spacing
    - collection_alignment
    - colon
    - comma
    - comment_spacing
    - compiler_protocol_init
    - computed_accessors_order
    - control_statement
    - custom_rules
    - deployment_target
    - discouraged_direct_init
    - duplicate_imports
    - dynamic_inline
    - empty_enum_arguments
    - empty_parameters
    - empty_parentheses_with_trailing_closure
    - explicit_init
    - file_name_no_space
    - force_try
    - implicitly_unwrapped_optional
    - inert_defer
    - is_disjoint
    - leading_whitespace
    - legacy_cggeometry_functions
    - legacy_constant
    - legacy_constructor
    - legacy_hashing
    - legacy_nsgeometry_functions
    - legacy_random
    - literal_expression_end_indentation
    - mark
    - modifier_order
    - no_fallthrough_only
    - no_space_in_method_call
    - nsobject_prefer_isequal
    - opening_brace
    - operator_usage_whitespace
    - optional_enum_case_matching
    - prefer_zero_over_explicit_init
    - private_over_fileprivate
    - private_unit_test
    - protocol_property_accessors_order
    - redundant_discardable_let
    - redundant_objc_attribute
    - redundant_optional_initialization
    - redundant_void_return
    - return_arrow_whitespace
    - sorted_imports
    - statement_position
    - superfluous_disable_command
    - syntactic_sugar
    - trailing_newline
    - trailing_semicolon
    - trailing_whitespace
    - unneeded_break_in_switch
    - unowned_variable_capture
    - unused_control_flow_label
    - vertical_whitespace
    - vertical_whitespace_closing_braces
    - void_return

excluded:
    - Pods/

